# Generated by Django 2.1.7 on 2022-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productuser', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
