# Generated by Django 2.1.7 on 2022-04-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productuser', '0003_auto_20220417_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Own',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
